### ISSUE TITLE
Add Login Page 

### ISSUE THREAD

**Issue by soorajshankar** [TailAdmin/free-nextjs-admin-dashboard#15]
Would be nice to have a login page too!

Nicely crafted project, thanks for making the world better.

**Comment by zbkazi** [comment]
**Authentication has both sign in and sign up pages inside and more features you can try for premium you will surely like it**

![image](https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/153954612/71566895-60b5-4e5f-9e73-b0d04a492ebf)
