### ISSUE TITLE
Hook Dropdowns in the Header

### ISSUE THREAD

**Issue by japhernandez** [TailAdmin/free-nextjs-admin-dashboard#17]
In the three Dropdowns that are used in the Header, the logic for their operation is repeated.

DropdownMessages
DropdownNotification
DropdownUser

![hook](https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/48869934/c573d7aa-ee29-4312-bd65-06859ed0b620)

Implementation

![dropdown](https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/48869934/66b9f757-5353-4a1b-a355-8e258e2e20d4)

**Comment by Juhan-Ahamed** [comment]
We have updated this with a new component called ClickOutside
