### ISSUE TITLE
Make the sidebar collapsible

### ISSUE THREAD

**Issue by wahab896** [TailAdmin/free-nextjs-admin-dashboard#18]
It would look good to have a collapsible sidebar which will not entirely collapse but it will show just the icons to the right and could have expand feature that would overlay to the main screen, as shown in the mobile layout.

**Comment by Juhan-Ahamed** [comment]
Thank you for your suggestion!

We appreciate your input on having a collapsible sidebar that shows only icons when collapsed and expands to overlay the main screen. While this is a great idea and could enhance the user experience, we currently do not plan to implement this feature.
We will keep this suggestion in mind for future updates and enhancements. In the meantime, if you have any other suggestions or feedback, please feel free to share!

Thank you for your understanding.
