### ISSUE TITLE
[iOS] App crash when navigating from home page to another page 

### ISSUE THREAD

**Issue by ngothiensinh** [TailAdmin/free-nextjs-admin-dashboard#28]
Device:
- iOS 17.5.1 (iPhone 13 mini)
- Browser: Chrome, Safari

Steps:
- Access: https://nextjs-demo.tailadmin.com/
- You are on the home page
- Open the hamburger button, navigate to Calendar
- Actual: Show error, and only works if you refresh the page
- Expected: Able to navigate to another page from the home page without any error

Image:
- ![448503791_434214659583757_8959971962953828829_n](https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/19794558/7452edfb-f54b-4696-bcf2-7e18c27f750b)

I also try to pull the code and deploy myself in both modes: Docker and Static - same issue. I think some error on the Homepage prevents navigation, but no MacBook for debugging.

**Comment by ngothiensinh** [comment]
The issue causes the js map vector.

**Comment by Coderamrin** [comment]
Resolved!
