### ISSUE TITLE
Nextjs 14 compatibility

### ISSUE THREAD

**Issue by Jorgelig** [TailAdmin/free-nextjs-admin-dashboard#6]
Are there plans to make it compatible with nextjs 14?

**Comment by Musharofchy** [comment]
Soon :)

**Comment by jdnielss** [comment]
can't wait~~~

**Comment by MorganFrary** [comment]
Do you guys have any ETAs on this or is this a "when it's done" situation?
Looking forward to it regardless 👍

**Comment by Musharofchy** [comment]
> Do you guys have any ETAs on this or is this a "when it's done" situation? Looking forward to it regardless 👍

This week, for sure 🤗

**Comment by Musharofchy** [comment]
TailAdmin is now compatible with Next.js 14
