### ISSUE TITLE
Double scrollbar on mobile

### ISSUE THREAD

**Issue by mtnair** [TailAdmin/free-nextjs-admin-dashboard#7]
I found a bug on mobile screens, there is a double scrollbar. When scrolling to the very bottom of a page, the navbar disappears and you have to scroll to the very top to make it visible again.
I expect it to be sticky all the time.
Here is a screenshot of the double scrollbars:
![image](https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/1964346/636e7cd8-a52d-4980-bd72-fd8e0d33caec)

**Comment by Coderamrin** [comment]
Hello @mtnair which browser are you testing on?
I've tried it on Chrome and Brave (on mobile) it looks okay. 

https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/52592047/b84e2d94-f5f4-420a-89f3-c5b582f9249f

https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/52592047/2506f459-f432-401f-90bb-32485774eacf

let me know which browser is it I'll take a look

**Comment by mtnair** [comment]
I tried it in Safari on iOS, but it also happens in Chrome on iOS. In Android browsers I didn't have these problems.
See following videos:

Safari (iPhone):

https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/1964346/5b15abb1-9e45-464a-9e48-7e9271282cb5

Chrome (iPhone):

https://github.com/TailAdmin/free-nextjs-admin-dashboard/assets/1964346/f0879377-700a-4d02-a04c-bad8f41ec8bb
